---
version: 2
project_name: qbrr

before:
  hooks:
    - go mod tidy

builds:
  - id: qbrr
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./main.go
    binary: qbrr

upx:
  - enabled: true
    compress: best
    lzma: true
